# Generated by Django 5.2.6 on 2025-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('apparel', 'Apparel'), ('accessories', 'Accessories'), ('training', 'Training'), ('equipment', 'Equipment'), ('ball', 'Ball'), ('fans', 'Fans Merchandise')], max_length=100)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('product_likes', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
